name: Generate Snake

on:
  schedule: # roda automaticamente a cada 24h
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente
  push: # roda quando tiver push
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: seuusuario
          outputs: dist/github-contribution-grid-snake.svg

      - name: Deploy Snake Animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
